# Generated by Django 5.2.13 on 2026-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('disease_code', models.CharField(max_length=10)),
                ('disease_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('care_suggestion', models.TextField()),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
